### ISSUE TITLE
html 4 runtime cannot be instantiate correctly

### ISSUE THREAD

**Issue by mgrigis** [paddle8/ember-plupload#28] opened 2015-07-03 15:34 UTC
When i try to instantiate html4 on any browser (FF, Chrome, IE) i have an error at the end.

here is my handlebar

```javascript
{{#pl-uploader extensions="pdf doc docx xls xlsx ppt pptx" runtimes="html4,flash" for="newDoc" when-queued="uploadDoc" max-file-size="1024kb" as |queue dropzone|}}
        <a class="btn btn-primary" title="{{format-message (intl-get 'common.browse')}}" id="newDoc </a>
{{/pl-uploader}}

```
Result in debug console : 

Instantiating FileInput...
moxie.js:1176 Trying runtime: html4
moxie.js:1176 Object {accept: Array[1], name: "file", multiple: true, required_caps: Object, container: "ember1386"…}
moxie.js:1176 	default mode: browser
moxie.js:1176 	selected mode: browser
moxie.js:1176 Runtime 'html4' initialized
moxie.js:1176 Instantiating FileDrop...
moxie.js:1176 Trying runtime: html4
moxie.js:1176 Object {accept: Array[1], required_caps: Object, runtime_order: "html4,flash", preferred_caps: Object, swf_url: "/assets/Moxie.swf"…}
moxie.js:1176 	default mode: browser
moxie.js:1176 	selected mode: false
moxie.js:1176 Runtime 'html4' failed to initialize

It seems to be link that html4 rutime is not capable of drag_and_drop. 
The code failed here in moxie.js :

```javascript
if (this.mode && options.required_caps && !this.can(options.required_caps)) {
			this.mode = false;
		}	
```

**Comment by tim-evans** [comment] 2015-07-03 20:52
What version of plupload are you using?

I'm pretty sure that this was fixed by https://github.com/paddle8/ember-plupload/issues/17 through https://github.com/paddle8/ember-plupload/commit/1d3b8323000c39ec310df950ef56985ace10b614

**Comment by mgrigis** [comment] 2015-07-04 08:10
i'm using 2.1.3 an the last version of your lib 0.6.22

**Comment by tim-evans** [comment] 2015-07-04 15:56
The `runtimes` field is space separated, not comma separated. Also, I can't reproduce this by copy-pasting the template into a Ember app running 1.12 and 1.13.2 (and fixing a bug in the body of the plupload).

I recommend that you provide a `name` for your uploader so it starts back up with the correct state as well.

I'll need a reproducible test case to get this fixed.

**Comment by mgrigis** [comment] 2015-07-06 07:26
My app is running in 1.11.0.

**Comment by tim-evans** [comment] 2015-07-06 13:18
Is that your exact handlebars above?

**Comment by mgrigis** [comment] 2015-07-06 13:41
i change a little for this
```javascript
{{#pl-uploader extensions="pdf doc docx xls xlsx ppt pptx" runtimes="html4 flash" for="newDoc" when-queued="uploadDoc" max-file-size="1024kb" as |queue dropzone|}}
        <a class="btn btn-primary" title="browse" id="newDoc">browse</a>
      {{/pl-uploader}}
```

and i have some others stuff for my application nothing special

**Comment by mgrigis** [comment] 2015-07-07 09:48
Is there an option in order to not initialize drop area ?

**Comment by mgrigis** [comment] 2015-07-07 13:50
sorry i made a mistake it s with 2.1.6 plupload version

**Comment by mgrigis** [comment] 2015-07-10 08:36
ok with this commit https://github.com/paddle8/ember-plupload/commit/83d803e6ed0460875cdcca90633ed64cc90f4a7d

**Closed** 2015-07-10 17:53 UTC
